export * from './Home/Home.page';
export * from './Login/Login.page';
export * from './DemoComponents/DemoComponents.page';
export * from './Cart/Cart.page';
export * from './ProductDetail/ProductDetail.page';
export * from './ProductList/ProductList.page';
export * from './Profile/Profile.page';
export * from './Register/Register.page';
export * from './AddCreditCard/AddCreditCard.page';
