import bgImage from './images/login-bg.png';
import tma_hd_wireless_1 from './images/tma_hd_wireless_1.png';
import tma_hd_wireless_2 from './images/tma_hd_wireless_2.png';
import headphonesImage from './images/headphones.png';
import headphonesImageLg from './images/headphones_lg.png';
import avatarGeneric from './images/avatarGeneric.png';
import userImg from './images/user.png';

export * from './base/icons/arrow_banner_icon';
export * from './base/icons/arrow_icon';
export * from './base/icons/filter_icon';
export * from './base/icons/star_filled_icon';
export * from './base/icons/star_outlined_icon';
export * from './base/icons/minus_icon';
export * from './base/icons/more_vertical';
export * from './base/icons/plus_icon';
export * from './base/icons/trash_icon';
export * from './base/icons/cart_icon';
export * from './base/icons/chevron_left_icon';
export * from './base/icons/dip_core_logo';
export * from './base/icons/nri_logo';
export * from './base/icons/search_icon';

export const loginBackground = bgImage;
export const ProductImage1 = tma_hd_wireless_1;
export const ProductImage2 = tma_hd_wireless_2;
export const imageSmall = headphonesImage;
export const imageLarge = headphonesImageLg;
export const avatarImage = avatarGeneric;
export const userImage = userImg;
